### ISSUE TITLE
生成的中文注释中文

### ISSUE THREAD

**Issue by baxiaowei** [mizhoux/mbg-comment#2]
您好，我这里生成的中文注释是乱码的。
/**
 * è®¢å�•è¡¨
 *
 * @author
 * @time   2020/04/29 17:41
 */
public class McfWcbOrder {
    /**
     * è®¢å�•è¡¨ä¸»é”®
     */
    private Long id;

    /**
     * è®¢å�•æ‰€å±žäºº

这是哪里的问题呢？

**Comment by mizhoux** [comment]
MySQL 数据库的编码要设置为 UTF-8 哦：
```sql
CREATE TABLE `table_name`
(
    ...
)
DEFAULT CHARSET=utf8mb4;
```
